import {
  GogoCDN,
  StreamSB,
  VidCloud,
  MixDrop,
  Kwik,
  RapidCloud,
  MegaCloud,
  StreamTape,
  VizCloud,
  Filemoon,
  BilibiliExtractor,
  AsianLoad,
  SmashyStream,
  StreamHub,
  VidMoly,
} from '../extractors';
import {
  USER_AGENT,
  splitAuthor,
  floorID,
  formatTitle,
  genElement,
  capitalizeFirstLetter,
  range,
  getDays,
  days,
  isJson,
  convertDuration,
  substringAfter,
  substringBefore,
  compareTwoStrings,
} from './utils';
import {
  anilistSearchQuery,
  anilistMediaDetailQuery,
  kitsuSearchQuery,
  anilistTrendingQuery,
  anilistPopularQuery,
  anilistAiringScheduleQuery,
  anilistGenresQuery,
  anilistAdvancedQuery,
  anilistSiteStatisticsQuery,
  anilistCharacterQuery,
} from './queries';
import { parsePostInfo } from './getComics';

export {
  USER_AGENT,
  GogoCDN,
  StreamSB,
  SmashyStream,
  StreamHub,
  splitAuthor,
  floorID,
  formatTitle,
  parsePostInfo,
  genElement,
  capitalizeFirstLetter,
  VidCloud,
  MixDrop,
  Kwik,
  anilistSearchQuery,
  anilistMediaDetailQuery,
  kitsuSearchQuery,
  range,
  RapidCloud,
  MegaCloud,
  StreamTape,
  VizCloud,
  anilistTrendingQuery,
  anilistPopularQuery,
  anilistAiringScheduleQuery,
  anilistGenresQuery,
  anilistAdvancedQuery,
  anilistSiteStatisticsQuery,
  Filemoon,
  anilistCharacterQuery,
  getDays,
  days,
  isJson,
  convertDuration,
  BilibiliExtractor,
  AsianLoad,
  substringAfter,
  substringBefore,
  compareTwoStrings,
  VidMoly,
};
